services:
  - type: web
    name: print-service
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'self' https://secure-print-docs-2025.s3.eu-north-1.amazonaws.com"
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 