services:
  - type: web
    name: print-service
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /print
        destination: /index.html
      - type: rewrite
        source: /print/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'self' https://secure-print-docs-2025.s3.eu-north-1.amazonaws.com"
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 